# Generated by Django 3.2.7 on 2021-12-09 11:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('data', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
